---
resources:
  - name: git-buildout-image
    icon: git
    type: git
    check_every: 600s
    source:
      uri: https://github.com/gotcha/buildout_docker_alpine.git
      branch: concourse/zope
  - name: buildout-image
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/buildout-docker-alpine
      insecure_registries:
        - "registry:5000"
  - name: python-image
    icon: docker
    type: docker-image
    source:
      repository: python
      tag: 2.7-alpine3.9
  - name: zope-image
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/zope-alpine
      insecure_registries:
        - "registry:5000"
  - name: zope-image-builder
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/zope-alpine-builder
      insecure_registries:
        - "registry:5000"
jobs:
  - name: zope-image-bootstrap
    old_name: zope-image-builder
    public: true
    plan:
      - in_parallel:
          - get: git-buildout-image
          - get: buildout-image
            params:
              save: true
          - get: python-image
            params:
              save: true
      - put: zope-image-builder
        params:
          load_base: buildout-image
          build: git-buildout-image/ci/pipelines/zope
          target_name: builder
      - put: zope-image
        params:
          load_base: buildout-image
          build: git-buildout-image/ci/pipelines/zope
          tag_as_latest: true
  - name: zope-image
    public: true
    plan:
      - in_parallel:
          - get: git-buildout-image
            trigger: true
          - get: python-image
            params:
              save: true
          - get: buildout-image
            params:
              save: true
            trigger: true
          - get: zope-image-builder
            passed: [zope-image-bootstrap]
            params:
              save: true
          - get: zope-image
            passed: [zope-image-bootstrap]
            params:
              save: true
      - in_parallel:
          - put: zope-image-builder
            params:
              cache_from:
                - python-image
                - zope-image-builder
              load_base: buildout-image
              build: git-buildout-image/ci/pipelines/zope
              target_name: builder
          - put: zope-image
            params:
              cache: true
              cache_tag: latest
              cache_from:
                - python-image
                - zope-image-builder
                - zope-image
              load_base: buildout-image
              build: git-buildout-image/ci/pipelines/zope
  - name: start-zope
    public: true
    plan:
      - in_parallel:
        - get: git-buildout-image
        - get: zope-image
          passed: [zope-image]
          trigger: true
          params:
            save: true
      - task: start-zope
        image: zope-image
        config:
          inputs:
            - name: git-buildout-image
          platform: linux
          run:
            path: git-buildout-image/ci/pipelines/zope/test.sh
      - put: zope-image
        params:
          load: zope-image
          tag_as_latest: true
