---
resources:
  - name: git-buildout-image
    icon: git
    type: git
    check_every: 10s
    source:
      uri: https://github.com/gotcha/buildout_docker_alpine.git
      branch: concourse/zope 
  - name: buildout-image
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/buildout-docker-alpine
      insecure_registries: 
        - "registry:5000"
  - name: zope-image
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/zope-alpine
      insecure_registries: 
        - "registry:5000"
  - name: zope-image-builder
    icon: docker
    type: docker-image
    source:
      repository: registry:5000/gotcha/zope-alpine-builder
      insecure_registries: 
        - "registry:5000"
jobs:
  - name: zope-image-builder
    public: true
    plan:
      - in_parallel:
          - get: git-buildout-image
          - get: buildout-image
            params:
              save: true
            trigger: true
      - put: zope-image-builder
        params:
          load_base: buildout-image
          build: git-buildout-image/ci/pipelines/zope
          target_name: builder
  - name: zope-image
    public: true
    plan:
      - in_parallel:
          - get: git-buildout-image
            trigger: true
          - get: buildout-image
            params:
              save: true
            trigger: true
          - get: zope-image-builder
            passed: [zope-image-builder]
            params:
              save: true
      - put: zope-image
        params:
          cache_from:
            - zope-image-builder
          load_base: buildout-image
          build: git-buildout-image/ci/pipelines/zope
      - put: zope-image-builder
        params:
          cache_from:
            - zope-image-builder
          load_base: buildout-image
          build: git-buildout-image/ci/pipelines/zope
          target_name: builder
  - name: start-zope
    public: true
    plan:
      - in_parallel:
        - get: git-buildout-image
        - get: zope-image
          passed: [zope-image]
          trigger: true
          params:
            save: true
      - task: start-zope
        image: zope-image
        config:
          inputs:
            - name: git-buildout-image
          platform: linux
          run:
            path: git-buildout-image/ci/pipelines/zope/test.sh
      - put: zope-image
        params:
          load: zope-image
          tag_as_latest: true
