name: Fun with concourse
on: [push]

jobs:
  build:
    name: Concourse
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start concourse
      run: docker-compose -f ${GITHUB_WORKSPACE}/ci/docker-compose.yml up -d
    - name: Launch job
      working-directory: ${GITHUB_WORKSPACE}
      run: make start
    - name: Watch job
      working-directory: ${GITHUB_WORKSPACE}
      run: ./fly -t buildout-ci w --job=zope/zope-image-bootstrap
